
title:  Nixies Journal 
email: 
description: >
baseurl: ""
url: ""

# Build settings
markdown: kramdown

twitterUsername:
gthubUsername:

social:
  github: 
  stackoverflow: ''
  linkedin:
  instagram: ''
  lastfm: ''
  rss: feed.xml

themeColor: default
fixedNav: 'true'

permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, LICENSE, README.md]
sass:
  style: compressed
