
title: Nixies Journal 
email: 
description: >
baseurl: ""
url: ""

# Build settings
markdown: kramdown

twitterUsername: nixiesjournal
gthubUsername: nixiesjournal



themeColor: default
fixedNav: 'true'

permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, LICENSE, README.md]
sass:
  style: compressed
